const signUpEndPoint = 'https://stacked.com.ng/api/register';
const signInEndPoint = 'https://stacked.com.ng/api/login';
const userDataEndPoint = 'https://stacked.com.ng/api/profile';
const contentType = 'Content-Type';
const jsonFormat = 'application/json';
const accept = 'Accept';
const token = 'token';
const bearer = 'Bearer ';
const authorization = 'Authorization';